import { writeFileSync } from "node:fs";
import type { Plugin } from "vite";
import { defineConfig } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

const stringifyHtml = (output: string): Plugin => ({
  name: "workspace-ssh-terminal-html-stringify",
  enforce: "post",
  generateBundle(_, bundle) {
    for (const [fileName, assetInfo] of Object.entries(bundle)) {
      if (
        fileName.endsWith(".html") &&
        assetInfo &&
        typeof assetInfo === "object" &&
        "source" in assetInfo &&
        typeof assetInfo.source === "string"
      ) {
        writeFileSync(
          output,
          [
            "/**",
            " * This file is generated by the workspace SSH terminal build.",
            " * Do not edit this file directly.",
            " */",
            `export default ${JSON.stringify(assetInfo.source)}`,
          ].join("\n"),
        );
      }
    }
  },
});

export default defineConfig({
  build: {
    assetsInlineLimit: 1024 * 1024,
    emptyOutDir: true,
    outDir: "../../dist/workspace-ssh-terminal",
    target: "es2020",
  },
  plugins: [
    viteSingleFile({
      deleteInlinedFiles: true,
      removeViteModuleLoader: true,
    }),
    stringifyHtml("./src/components/chat/workspace-preview/workspace-ssh-terminal-html.ts"),
  ],
  publicDir: false,
  root: "./web/workspace-ssh-terminal",
  server: {
    host: "127.0.0.1",
    port: 30000,
    strictPort: true,
  },
});
